
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-servicemanager-servicemanager-io-v1-servicemanager
  failurePolicy: Fail
  name: mservicemanager.kb.io
  rules:
  - apiGroups:
    - servicemanager.servicemanager.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - servicemanagers

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-servicemanager-servicemanager-io-v1-servicemanager
  failurePolicy: Fail
  name: vservicemanager.kb.io
  rules:
  - apiGroups:
    - servicemanager.servicemanager.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - servicemanagers
