
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployment
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - statefulSet
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - service
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - servicemanager.servicemanager.io
  resources:
  - servicemanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - servicemanager.servicemanager.io
  resources:
  - servicemanagers/status
  verbs:
  - get
  - patch
  - update
