# permissions for end users to view servicemanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicemanager-viewer-role
rules:
- apiGroups:
  - servicemanager.servicemanager.io
  resources:
  - servicemanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - servicemanager.servicemanager.io
  resources:
  - servicemanagers/status
  verbs:
  - get
