# permissions for end users to edit servicemanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicemanager-editor-role
rules:
- apiGroups:
  - servicemanager.servicemanager.io
  resources:
  - servicemanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - servicemanager.servicemanager.io
  resources:
  - servicemanagers/status
  verbs:
  - get
